version: 2
jobs:
  lint:
    working_directory: /workspace/infrastructure
    docker:
      - image: smartcontract/builder:1.0.10
    steps:
      - checkout
      - run: kubeval k8s/templates/*

workflows:
  version: 2
  test:
    jobs:
      - lint
