---
kind: Service
apiVersion: v1
metadata:
  name: chainlink-svc
spec:
  type: LoadBalancer
  selector:
    app: chainlink
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 6688
    - name: https
      protocol: TCP
      port: 443
      targetPort: 6689
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: chainlink-deploy
spec:
  selector:
    matchLabels:
      app: chainlink
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chainlink
    spec:
      containers:
        - name: chainlink
          image: smartcontract/chainlink:latest
          args: ["node", "-p", "/secrets/password/password", "-a", "/secrets/api/api"]
          ports:
            - containerPort: 6688
            - containerPort: 6689
          env:
            - name: ROOT
              value: "/data/chainlink"
            - name: ETH_URL
              valueFrom:
               configMapKeyRef:
                 name: chainlink-cfg
                 key: ETH_URL
            - name: ALLOW_ORIGINS
              value: "*"
            - name: CHAINLINK_TLS_HOST
              valueFrom:
               configMapKeyRef:
                 name: chainlink-cfg
                 key: CHAINLINK_TLS_HOST
            - name: TLS_CERT_PATH
              value: /secrets/tls/tls.crt
            - name: TLS_KEY_PATH
              value: /secrets/tls/tls.key
          envFrom:
            - secretRef:
                name: cl-environment
          volumeMounts:
            - name: chainlink-storage
              mountPath: /data
            - name: chainlink-password
              mountPath: /secrets/password
              readOnly: true
            - name: chainlink-api
              mountPath: /secrets/api
              readOnly: true
            - name: chainlink-crt
              mountPath: /secrets/tls
              readOnly: true
      volumes:
        - name: chainlink-storage
          persistentVolumeClaim:
            claimName: chainlink-pv-claim
        - name: chainlink-password
          secret:
            secretName: cl-password
        - name: chainlink-api
          secret:
            secretName: cl-api
        - name: chainlink-crt
          secret:
            secretName: cl-sslcert
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: chainlink-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
