---
kind: Service
apiVersion: v1
metadata:
  name: ethereum-svc
spec:
  selector:
    app: ethereum
  ports:
    - name: rpc
      protocol: TCP
      port: 8545
    - name: ws
      protocol: TCP
      port: 8546
    - name: listening
      protocol: TCP
      port: 30303
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethereum-deploy
spec:
  selector:
    matchLabels:
      app: ethereum
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ethereum
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - name: listening
              protocol: TCP
              containerPort: 30303
            - name: discovery
              protocol: UDP
              containerPort: 30303
          volumeMounts:
            - name: ethereum-crt
              mountPath: /secrets/tls
              readOnly: true
            - name: nginx-conf-volume
              mountPath: /etc/nginx/conf.d
        - name: ethereum
          image: ethereum/client-go:latest
          args: ["--syncmode", "$(SYNCMODE)", "--$(CHAIN)", "--port", "60303", "--ws", "--wsport", "18546", "--wsaddr", "0.0.0.0", "--wsorigins", "*", "--rpc", "--rpcport", "18545", "--rpcaddr", "0.0.0.0", "--rpccorsdomain", "*", "--datadir", "/data/ethereum", "--ipcdisable"]
          env:
            - name: CHAIN
              valueFrom:
               configMapKeyRef:
                 name: ethereum-cfg
                 key: CHAIN
            - name: SYNCMODE
              valueFrom:
               configMapKeyRef:
                 name: ethereum-cfg
                 key: SYNCMODE
          volumeMounts:
            - name: ethereum-storage
              mountPath: /data
      volumes:
        - name: ethereum-storage
          persistentVolumeClaim:
            claimName: ethereum-pv-claim
        - name: ethereum-crt
          secret:
            secretName: ethereum-sslcert
        - name: nginx-conf-volume
          configMap:
            name: nginx-configmap
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ethereum-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    server {
      listen 8545 ssl;
      ssl_certificate           /secrets/tls/tls.crt;
      ssl_certificate_key       /secrets/tls/tls.key;
      location / {
        proxy_pass  http://localhost:18545;
      }
    }

    server {
      listen 8546 ssl;
      ssl_certificate           /secrets/tls/tls.crt;
      ssl_certificate_key       /secrets/tls/tls.key;

      location / {
        proxy_http_version 1.1;

        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_pass  http://localhost:18546;
      }
    }

    server {
      listen 30303 ssl;
      ssl_certificate           /secrets/tls/tls.crt;
      ssl_certificate_key       /secrets/tls/tls.key;
      location / {
        proxy_pass  http://localhost:60303;
      }
    }
