kind: Service
apiVersion: v1
metadata:
  name: ethereum-svc
spec:
  selector:
    app: ethereum
  ports:
    - name: rpc
      protocol: TCP
      port: 8545
    - name: ws
      protocol: TCP
      port: 8546
    - name: listening
      protocol: TCP
      port: 30303
  type: LoadBalancer
